<<<<<<< HEAD
services:
  - type: web
    name: devops-nodejs-webapp
    runtime: docker
    plan: free
    region: oregon
    dockerfilePath: ./Dockerfile
    dockerContext: .
    healthCheckPath: /health
    autoDeployTrigger: checksPass
    envVars:
      - key: NODE_ENV
        value: production
      - key: DB_PATH
        value: /app/data/app.db
      - key: LOG_LEVEL
        value: info
=======
services:
  - type: web
    name: devops-nodejs-webapp
    runtime: docker
    plan: free
    region: oregon
    dockerfilePath: ./Dockerfile
    dockerContext: .
    healthCheckPath: /health
    autoDeployTrigger: checksPass
    envVars:
      - key: NODE_ENV
        value: production
      - key: DB_PATH
        value: /app/data/app.db
      - key: LOG_LEVEL
        value: info
>>>>>>> a0abb9c46a451e925c62d238c6108711908047d6
